import React from 'react';
import ReactDOM from 'react-dom';
import Router from './router';
import { Provider } from 'react-redux';
import { store } from './utilities/store';
import App from './loaders/chrome/chrome-loader';
import { IntlProvider } from 'react-intl';

// Entrypoint for compiling the app to run in insights dev mode.

ReactDOM.render(
  <Provider store={store(true)}>
    <IntlProvider locale="en">
      <Router>
        <App />
      </Router>
    </IntlProvider>
  </Provider>,

  document.getElementById('root')
);

/**
 * Register simple service worker JS assets pre cache
 * If registration fails, the app will continue to work without any issues.
 * Service worker is generated by webpack and should be ever available only in production version of the app.
 * You don't want your JS bundles to be cached in dev env.
 * You must test it locally in non HTTPS environment due to the insecure origin and self signed certificate issues cause by the PROXY.
 * These cannot be overcome due to xss security policy inside service workers browser implementation to avoid potential security issues.
 */
if (navigator.serviceWorker) {
  navigator.serviceWorker
    .register(
      `${
        window.location.pathname.includes('/beta') ? '/beta' : ''
      }/apps/catalog/service-worker.js`
    )
    .then((...args) => console.log('Service worker registered with: ', args))
    .catch(console.log);
}
